IgnisDa/ryot

- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/backend/src/media/resolver.rs
- apps/frontend/src/pages/list.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Search in user media

- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/config.rs
- apps/backend/src/importer/goodreads.rs
- apps/backend/src/main.rs
- apps/backend/src/media/resolver.rs
- apps/backend/src/users/resolver.rs
- apps/frontend/src/pages/list.tsx
- apps/frontend/src/pages/media/index.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Summary perf

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/goodreads.rs
- apps/backend/src/importer/media_tracker.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/users/resolver.rs
- apps/frontend/package.json
- apps/frontend/src/lib/layouts/LoggedIn.tsx
- apps/frontend/src/lib/services/api.ts
- apps/frontend/src/lib/utilities.ts
- apps/frontend/src/pages/_app.tsx
- apps/frontend/src/pages/collections.tsx
- apps/frontend/src/pages/index.tsx
- apps/frontend/src/pages/list.tsx
- apps/frontend/src/pages/media/index.tsx
- apps/frontend/src/pages/settings.tsx
- docs/guides/importing.md
- libs/generated/src/graphql/backend/graphql.ts
- yarn.lock
> General fixes and improvements

- Cargo.lock
- apps/backend/Cargo.toml
- apps/frontend/src/pages/list.tsx
- apps/frontend/src/pages/media/index.tsx
> Manual percentage

- CHANGELOG.md
- Cargo.lock
- apps/backend/Cargo.toml
- apps/frontend/src/lib/components/Grid.tsx
- apps/frontend/src/pages/_app.tsx
> Column layout issues

- CHANGELOG.md
- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/misc/mod.rs
- apps/backend/src/misc/resolver.rs
- apps/frontend/src/pages/collections.tsx
- libs/generated/src/graphql/backend/gql.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/graphql/src/backend/mutations/DeleteCollection.gql
> Allow deleting collections

- CHANGELOG.md
- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/backend/src/config.rs
- apps/backend/src/main.rs
> Serve config at endpoint

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/media/resolver.rs
> Sort by rating

- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/backend/src/config.rs
- apps/backend/src/fitness/exercise/logic.rs
- apps/backend/src/graphql.rs
- apps/backend/src/importer/media_tracker.rs
- apps/backend/src/migrator/m20230410_000001_create_metadata.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/audible.rs
- apps/backend/src/providers/google_books.rs
- apps/backend/src/providers/igdb.rs
- apps/backend/src/providers/itunes.rs
- apps/backend/src/providers/listennotes.rs
- apps/backend/src/providers/mod.rs
- apps/backend/src/providers/openlibrary.rs
- apps/backend/src/providers/tmdb.rs
- apps/backend/src/utils.rs
- apps/frontend/src/pages/_app.tsx
- apps/frontend/src/pages/list.tsx
- apps/frontend/src/pages/media/index.tsx
- libs/generated/src/graphql/backend/gql.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/graphql/src/backend/mutations/CommitNext10PodcastEpisodes.gql
> Add some providers supported by Audiobookshelf

- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/frontend/src/pages/media/index.tsx
- apps/frontend/src/pages/media/update-progress.tsx
> Improvements

- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/importer/goodreads.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/importer/movary.rs
- apps/backend/src/importer/trakt.rs
- apps/backend/src/main.rs
- apps/backend/src/migrator/m20230509_000008_create_media_import_report.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/audible.rs
- apps/backend/src/providers/google_books.rs
- apps/backend/src/providers/igdb.rs
- apps/backend/src/providers/listennotes.rs
- apps/backend/src/providers/openlibrary.rs
- apps/backend/src/providers/tmdb.rs
- apps/frontend/src/pages/settings.tsx
- docs/guides/importing.md
- libs/generated/src/graphql/backend/graphql.ts
> Import from Movary

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/trakt.rs
- apps/backend/src/integrations/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/audible.rs
- apps/backend/src/providers/google_books.rs
- apps/backend/src/providers/igdb.rs
- apps/backend/src/providers/itunes.rs
- apps/backend/src/providers/listennotes.rs
- apps/backend/src/providers/openlibrary.rs
- apps/backend/src/providers/tmdb.rs
- apps/backend/src/utils.rs
Fixes https://github.com/06chaynes/surf-retry/issues/1 and https://github.com/06chaynes/surf-governor/issues/1
> Surf features

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/entities/seen.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/migrator/m20230419_000003_create_seen.rs
- apps/backend/src/migrator/m20230612_000009_add_dropped_field.rs
- apps/backend/src/migrator/m20230722_000019_add_state_field.rs
- apps/backend/src/migrator/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/frontend/src/pages/list.tsx
- apps/frontend/src/pages/media/index.tsx
- libs/generated/src/graphql/backend/gql.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/graphql/src/backend/queries/SeenHistory.gql
This will allow marking media items as `Dropped` or `On a hold`.
Fixes #198.
> Add new seen states

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
This includes logic for when to remove a show/podcast from the "in progress" collection. It is pretty complicated, and I am very proud of myself for coming up with it.
> After media seen

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/entities/creator.rs
- apps/backend/src/entities/review.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/migrator/m20230505_000006_create_review.rs
- apps/backend/src/migrator/m20230730_create_creator.rs
- apps/backend/src/migrator/m20230801_add_creator_id_field_to_review.rs
- apps/backend/src/migrator/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/backend/src/providers/tmdb.rs
- apps/frontend/src/lib/components/MediaItem.tsx
- apps/frontend/src/pages/media/item/index.tsx
- apps/frontend/src/pages/media/item/post-review.tsx
- apps/frontend/src/pages/media/people/index.tsx
- libs/generated/src/graphql/backend/gql.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/graphql/src/backend/queries/UserCreatorDetails.gql
> Allow reviewing creators

- .github/workflows/release.yml
- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/config.rs
- apps/backend/src/file_storage.rs
- apps/backend/src/fitness/exercise/resolver.rs
- apps/backend/src/graphql.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/main.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/routes.rs
- apps/backend/src/utils.rs
Related to https://www.reddit.com/r/rust/comments/15gz5tc/i_switched_to_using_global_variables_using/
> Reduce memory usage

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/config.rs
- apps/backend/src/file_storage.rs
- apps/backend/src/fitness/exercise/resolver.rs
- apps/backend/src/graphql.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/main.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/backend/src/routes.rs
- apps/backend/src/utils.rs
- apps/frontend/src/pages/media/item/index.tsx
- docs/includes/backend-config-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/utilities/src/index.ts
The scheduler database should not be file based.
> Remove file db

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/trakt.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/backend/src/notification.rs
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/audible.rs
- apps/backend/src/providers/google_books.rs
- apps/backend/src/providers/itunes.rs
- apps/backend/src/providers/openlibrary.rs
- apps/backend/src/users.rs
- apps/frontend/src/pages/media/list.tsx
- apps/frontend/src/pages/settings/notifications.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Support for Apprise

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/providers/tmdb.rs
- apps/frontend/src/pages/fitness/measurements.tsx
Download details of production companies.
> Tmdb companies

- Cargo.lock
- apps/backend/Cargo.toml
- docs/content/index.md
Let me know if this is what you had in mind :)
Fixes #290.
> doc: add cosmos as install method

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/config.rs
- apps/backend/src/migrator/m20230410_create_metadata.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/igdb.rs
- apps/backend/src/providers/manga_updates.rs
- apps/backend/src/providers/mod.rs
- apps/frontend/src/lib/components/MediaDetailsLayout.tsx
- docs/includes/backend-config-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/rs-utils/src/length_vec.rs
> Support Manga Updates

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/config.rs
- apps/backend/src/migrator/m20230410_create_metadata.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/mal.rs
- apps/backend/src/providers/mod.rs
- docs/includes/backend-config-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
> MAL support

- .gitignore
- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/mal.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/main.rs
- apps/backend/src/routes.rs
- apps/frontend/src/pages/media/item/create.tsx
- apps/frontend/src/pages/media/post-review.tsx
- apps/frontend/src/pages/settings/imports/index.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Write temp files to correct directory

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/tmdb.rs
> Incorrect avergae rating being returned

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/mod.rs
- apps/backend/src/importer/trakt.rs
> Trakt imports

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/config.rs
- apps/backend/src/main.rs
- apps/frontend/src/pages/index.tsx
- apps/frontend/src/pages/media/list.tsx
- docs/includes/backend-config-schema.ts
> Optimizations

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/notification.rs
- apps/backend/src/users/mod.rs
- apps/frontend/src/pages/settings/notifications.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Allow setting auth header for Ntfy

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/entities/user.rs
- apps/backend/src/fitness/resolver.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/utils.rs
- apps/frontend/src/pages/settings/preferences.tsx
- libs/generated/src/graphql/backend/graphql.ts
This also includes a lot of changes that should \*hopefully\* decrease memory usage.
> Reset preferences to default btn

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/entities/workout.rs
- apps/backend/src/importer/media_json.rs
- apps/backend/src/models.rs
- docs/includes/export-schema.ts
- libs/database/src/migrations/m20230410_create_metadata.rs
- libs/database/src/migrations/m20230622_create_exercise.rs
> Fix media json import

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/entities/review.rs
- apps/backend/src/miscellaneous/resolver.rs
- docs/content/migration.md
> Review comments column type and summary calculation bug

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/fitness/logic.rs
- apps/backend/src/importer/strong_app.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/src/lib/components/FitnessComponents.tsx
- apps/frontend/src/lib/layouts/LoggedIn.tsx
- apps/frontend/src/pages/index.tsx
- apps/frontend/src/pages/settings/imports-and-exports/index.tsx
- libs/generated/src/graphql/backend/graphql.ts
Fixes https://github.com/IgnisDa/ryot/issues/375.
Fixes https://github.com/IgnisDa/ryot/issues/421.
Fixes https://github.com/IgnisDa/ryot/issues/423.
> Workouts and other changes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
> Return correct value of next episode

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/frontend/src/pages/fitness/exercises/create-or-edit.tsx
- apps/frontend/src/pages/media/item/create.tsx
- apps/frontend/src/pages/settings/integrations.tsx
- apps/frontend/src/pages/settings/users.tsx
- docs/includes/export-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
Fixes #457 
Fixed all the typos encountered while using CSpell.
> Fixed the typos

- Cargo.lock
- apps/backend/Cargo.toml
- apps/frontend/package.json
- apps/frontend/src/lib/constants.ts
- apps/frontend/src/lib/workout.ts
- apps/frontend/src/pages/_app.tsx
- apps/frontend/src/pages/collections/index.tsx
- apps/frontend/src/pages/fitness/exercises/list.tsx
- apps/frontend/src/pages/fitness/measurements.tsx
- apps/frontend/src/pages/media/list.tsx
- apps/frontend/src/pages/media/people/list.tsx
- apps/frontend/src/styles/globals.css
- yarn.lock
The measurements will now be displayed in a table.
> Measurements display

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/src/components/FitnessComponents.tsx
- apps/frontend/src/components/MediaComponents.tsx
- apps/frontend/src/lib/workout.ts
- apps/frontend/src/pages/fitness/exercises/current-workout.tsx
- apps/frontend/src/pages/media/item/index.tsx
- apps/frontend/src/pages/settings/integrations.tsx
> Display only monitored media in upcoming section

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/mod.rs
- apps/backend/src/importer/strong_app.rs
- apps/backend/src/models.rs
- apps/backend/src/providers/audible.rs
- apps/frontend/src/components/FitnessComponents.tsx
- apps/frontend/src/lib/workout.ts
- apps/frontend/src/pages/_app.tsx
- apps/frontend/src/pages/fitness/exercises/current-workout.tsx
- apps/frontend/src/pages/fitness/exercises/workouts/list.tsx
- apps/frontend/src/pages/fitness/measurements.tsx
- apps/frontend/src/pages/media/genres/index.tsx
- apps/frontend/src/pages/settings/imports-and-exports/index.tsx
- biome.json
> General fixes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/fitness/resolver.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/frontend/src/pages/settings/miscellaneous.tsx
- apps/frontend/src/pages/settings/preferences.tsx
- libs/generated/src/graphql/backend/gql.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/graphql/src/backend/mutations/DeployBackgroundJob.gql
- libs/graphql/src/backend/mutations/DeployRecalculateCalendarEventsJob.gql
- libs/graphql/src/backend/mutations/RegenerateUserSummary.gql
- libs/graphql/src/backend/mutations/UpdateAllMetadata.gql
> Do not sort exercise muscles before comitting

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/vndb.rs
> Github rate limits and correct cover images

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/providers/anilist/media_details.graphql
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/anilist/search.graphql
- apps/frontend/src/lib/workout.ts
- apps/frontend/src/pages/fitness/exercises/current-workout.tsx
- docs/includes/backend-config-schema.ts
- libs/config/src/lib.rs
> Anilist english title

- docs/content/importing.md
Added information about the import from TvTime using https://github.com/SirMartin/TvTimeToRyot
> #484 Added doc about importing from TV Time

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/fitness/resolver.rs
- apps/frontend/src/pages/fitness/exercises/workouts/details.tsx
- apps/frontend/src/pages/settings/miscellaneous.tsx
- libs/database/src/migrations/m20230819_create_workout.rs
- libs/generated/src/graphql/backend/gql.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/graphql/src/backend/mutations/EditUserWorkout.gql
> Edit workout timings

- .devcontainer/docker-compose.yml
- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/fitness/logic.rs
- apps/backend/src/fitness/resolver.rs
> Process workouts in correct order

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/fitness/logic.rs
- apps/backend/src/fitness/resolver.rs
- apps/backend/src/importer/strong_app.rs
- apps/backend/src/models.rs
- docs/includes/export-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
This lays the foundation for adding exercise superset support.
> Exercise supersets

- .devcontainer/Dockerfile
- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/main.rs
- apps/frontend/app/routes/_dashboard.fitness.exercises.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.current.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.list.tsx
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.settings.miscellaneous.tsx
- apps/frontend/app/routes/_dashboard.tsx
- libs/ts-utils/tsconfig.json
Some other bug fixes for the major release.
> Common changes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/exporter.rs
- apps/backend/src/integrations.rs
> Audiobookshelf logging

- Cargo.lock
- apps/backend/Cargo.toml
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- docs/content/index.md
- docs/content/migration.md
> In progress seen update

- Cargo.lock
- Cargo.toml
- apps/backend/Cargo.toml
- libs/database/Cargo.toml
- libs/database/src/migrations/m20240109_remove_persons.rs
- package.json
- yarn.lock
Addresses some problems with the `v4.1.0` release.
> Person fixes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/backend/src/providers/google_books.rs
- apps/frontend/app/routes/_dashboard.settings.imports-and-exports._index.tsx
- apps/frontend/app/routes/auth.register.tsx
- docs/content/deployment.md
- docs/includes/backend-config-schema.yaml
- docs/includes/export-schema.ts
- libs/config/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
> General improvements

- Cargo.lock
- Cargo.toml
- Dockerfile
- apps/backend/Cargo.toml
- apps/backend/src/entities/seen.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/users.rs
- apps/frontend/app/lib/cookies.server.ts
- apps/frontend/app/lib/generals.ts
- apps/frontend/app/lib/hooks.ts
- apps/frontend/app/lib/workout.ts
- apps/frontend/app/routes/_dashboard._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.measurements.list.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.current.tsx
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/_dashboard.settings.imports-and-exports._index.tsx
- apps/frontend/app/routes/_dashboard.tsx
- libs/database/src/migrations/m20230419_create_seen.rs
- libs/database/src/migrations/m20240121_add_updated_at_to_seen.rs
- libs/database/src/migrations/m20240121_remove_useless_section_from_dashboard.rs
- libs/database/src/migrations/mod.rs
- libs/generated/src/graphql/backend/graphql.ts
Also
- Fixes #583.
- Fixes #586.
> Updated at array for seen

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- docs/includes/backend-config-schema.yaml
- libs/config/src/lib.rs
- libs/database/src/migrations/m20240121_remove_useless_section_from_dashboard.rs
- libs/database/src/migrations/m20240122_remove_useless_section_from_dashboard.rs
> Specify correct schema for migrations

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/backend/src/notification.rs
- apps/backend/src/providers/igdb.rs
- apps/backend/src/providers/tmdb.rs
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
This will change some queries to be more performant.
- Addresses #440.
- Fixes #596.
> Optimize queries

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/fitness/resolver.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/main.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/routes/_dashboard.collections.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.list.tsx
- apps/frontend/app/routes/_dashboard.fitness.measurements.list.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.current.tsx
- apps/frontend/app/routes/_dashboard.media.groups.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.people.$id._index.tsx
- libs/generated/src/graphql/backend/graphql.ts
- Fixes #603.
- Also fixes #605.
> Import bug

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/components/media.tsx
- apps/frontend/app/routes/_dashboard._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.create.tsx
- apps/frontend/app/routes/_dashboard.fitness.measurements.list.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.current.tsx
- apps/frontend/app/routes/_dashboard.fitness.workouts.list.tsx
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/actions.tsx
- Fixes #644.
- Fixes #642.
- Fixes #639.
- Addresses #440.
- Fixes #588.
> Routine changes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/frontend/app/routes/_dashboard._index.tsx
- libs/database/src/migrations/m20240325_add_correct_attribute_to_user_preferences.rs
- libs/database/src/migrations/mod.rs
> Migrate over remaining attributes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/lib/utilities.server.ts
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
> Use proxy for uploading files

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/goodreads.rs
- apps/backend/src/importer/imdb.rs
- apps/backend/src/importer/mal.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/importer/movary.rs
- apps/backend/src/importer/open_scale.rs
- apps/backend/src/importer/story_graph.rs
- apps/backend/src/importer/strong_app.rs
- apps/backend/src/models.rs
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.settings.imports-and-exports._index.tsx
- libs/database/src/definitions.rs
- libs/generated/src/graphql/backend/graphql.ts
- Fixes #618.
- Fixes #711.
- Fixes #768.
> New changes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/landing/astro.config.mjs
- apps/landing/src/data/landing.json
- apps/landing/src/layouts/Layout.astro
- libs/ts-utils/package.json
- libs/ts-utils/src/index.ts
- yarn.lock
> Incorrect conversion from ISO date

- Cargo.lock
- README.md
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/entities/metadata.rs
- apps/backend/src/entities/person.rs
- apps/backend/src/integrations.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
- apps/frontend/app/routes/_dashboard.settings.miscellaneous.tsx
- docs/content/configuration.md
- docs/content/guides/openid.md
- docs/content/integrations.md
- docs/includes/backend-config-schema.yaml
- libs/config/src/lib.rs
- libs/database/src/migrations/m20230410_create_metadata.rs
- libs/database/src/migrations/m20230413_create_person.rs
- libs/database/src/migrations/m20240504_add_columns_for_state_changes.rs
- libs/database/src/migrations/mod.rs
- libs/generated/src/graphql/backend/graphql.ts
> Deduplicate state changes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/background.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/routes/_dashboard.collections.$id._index.tsx
- apps/frontend/app/routes/_dashboard.collections.list.tsx
THis introduces jobs to cleanup some data.
> Cleanup data

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/providers/anilist/mod.rs
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
> Fix anilist edge case bug

- .github/workflows/release.yml
- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/entities/genre.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/routes/_dashboard.collections.$id._index.tsx
- apps/frontend/app/routes/_dashboard.collections.list.tsx
- apps/frontend/app/routes/_dashboard.media.groups.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.people.item.$id._index.tsx
> General changes

- apps/backend/src/importer/jellyfin.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/routes/_dashboard.settings.imports-and-exports._index.tsx
- docs/content/importing.md
- libs/generated/src/graphql/backend/graphql.ts
This allows importing shows and movies from Jellyfin.
> Jellyfin import

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/goodreads.rs
- apps/backend/src/importer/jellyfin.rs
- apps/backend/src/importer/mal.rs
- apps/backend/src/importer/media_tracker.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/importer/movary.rs
- apps/backend/src/importer/story_graph.rs
- apps/backend/src/importer/trakt.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/models.rs
Handle edge cases for getting media from Jellyfin.
> Jellyfin fixes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/jellyfin.rs
- apps/backend/src/importer/trakt.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/anilist/media_details.graphql
- apps/backend/src/providers/anilist/media_search.graphql
- apps/backend/src/providers/anilist/mod.rs
- apps/backend/src/providers/anilist/staff_details.graphql
- apps/backend/src/providers/anilist/studio_details.graphql
- apps/backend/src/providers/tmdb.rs
- apps/frontend/app/routes/_dashboard.calendar.tsx
- apps/frontend/app/routes/_dashboard.settings.imports-and-exports._index.tsx
- apps/frontend/app/routes/_dashboard.settings.integrations.tsx
- apps/frontend/app/routes/_dashboard.settings.notifications.tsx
> Some common fixes

- Cargo.lock
- apps/backend/Cargo.toml
- apps/backend/src/importer/audiobookshelf.rs
- apps/backend/src/importer/mod.rs
- apps/backend/src/integrations.rs
- apps/backend/src/miscellaneous/mod.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/providers/google_books.rs
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- docs/content/importing.md
- docs/content/integrations.md
> Audiobookshelf improvements

- apps/backend/src/miscellaneous/resolver.rs
- apps/backend/src/notification.rs
- apps/backend/src/users.rs
- apps/frontend/app/routes/_dashboard.settings.notifications.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Telegram notifications

- apps/backend/src/entities/integration.rs
- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/routes/_dashboard.settings.integrations.tsx
- docs/content/integrations.md
- docs/includes/backend-config-schema.yaml
- libs/config/src/lib.rs
- libs/database/src/migrations/m20240607_create_integration.rs
- libs/database/src/migrations/m20240620_add_minimum_and_maximum_progress_columns_to_integration.rs
- libs/database/src/migrations/mod.rs
- libs/generated/src/graphql/backend/graphql.ts
> Integration level progress limit

- apps/backend/src/miscellaneous/resolver.rs
- apps/frontend/app/routes/api.auth.tsx
> Minor fixes

- Cargo.lock
- README.md
- apps/backend/src/integrations.rs
- apps/backend/src/miscellaneous.rs
- docs/content/integrations.md
- libs/database/src/definitions.rs
- libs/generated/src/graphql/backend/graphql.ts
Moved over to this branch for emby integration related code.
Note from original PR #926
Added emby integration this could possibly be integrated into the jellyfin integration but there are a decent amount of differences so we should probably keep them separate.
I am planning to add emby as an import source as well but this should probably be done in the future in a separate PR.
Fixes #187.
> Emby integration

- apps/backend/src/miscellaneous.rs
This function will mark unseen shows as finished since all episodes are marked 0 views which is == to the max of 0 shows
> Fixed bug in is_metadata_finished_by_user

- apps/backend/src/providers/manga_updates.rs
I have updated the manga_updates to include the volume and status
> manga_updates includes the volume count and publication status.

- apps/backend/src/miscellaneous.rs
- apps/backend/src/utils.rs
- apps/frontend/app/components/common.tsx
- apps/frontend/app/lib/generals.ts
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/_dashboard.media.groups.$action.tsx
- apps/frontend/app/routes/_dashboard.media.people.$action.tsx
- apps/frontend/app/routes/_dashboard.settings.integrations.tsx
- libs/generated/src/graphql/backend/graphql.ts
> Multiple collection filters

- apps/frontend/app/lib/generals.ts
- apps/frontend/app/lib/utilities.server.ts
- apps/frontend/app/routes/_dashboard.collections.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.$entity.list.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.list.tsx
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/_dashboard.media.genre.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.genre.list.tsx
- apps/frontend/app/routes/_dashboard.media.groups.$action.tsx
- apps/frontend/app/routes/_dashboard.media.people.$action.tsx
- apps/frontend/app/routes/actions.tsx
> Redirect to page 1 if on invalid page

- apps/frontend/app/components/common.tsx
- apps/frontend/app/components/media.tsx
- apps/frontend/app/lib/generals.ts
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.tsx
- crates/models/user/src/lib.rs
- crates/services/importer/src/lib.rs
- crates/services/miscellaneous/src/lib.rs
- crates/utils/database/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/ts-utils/src/index.ts
> 3 point smiley rating

- crates/services/fitness/src/lib.rs
> Issue 1020

- .github/workflows/main.yml
- Cargo.lock
- Cargo.toml
- apps/frontend/app/lib/generals.ts
- apps/frontend/app/lib/state/collection.ts
- apps/frontend/app/routes/_dashboard.collections.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/_dashboard.media.groups.$action.tsx
- apps/frontend/app/routes/_dashboard.media.people.$action.tsx
- apps/frontend/app/routes/_dashboard.tsx
- apps/frontend/app/routes/actions.tsx
- crates/models/media/src/lib.rs
- crates/services/collection/src/lib.rs
- crates/services/miscellaneous/src/lib.rs
- crates/services/statistics/src/lib.rs
- crates/services/user/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/transactional/tsconfig.json
- libs/ts-utils/src/index.ts
> Bulk add items to collection

- apps/frontend/app/routes/_dashboard.tsx
> Allow collapsing sidebar in desktop mode

- crates/providers/src/openlibrary.rs
- crates/services/importer/src/audiobookshelf.rs
- crates/services/importer/src/goodreads.rs
- crates/services/importer/src/lib.rs
- crates/services/importer/src/story_graph.rs
- crates/utils/dependent/src/lib.rs
- docs/content/configuration.md
> Better strategy for getting identifier from book ISBN

- apps/frontend/app/routes/_dashboard.fitness.exercises.$action.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.item.$id._index.tsx
- crates/models/database/src/exercise.rs
- crates/models/dependent/src/lib.rs
- crates/models/fitness/src/lib.rs
- crates/services/fitness/src/lib.rs
- crates/utils/dependent/src/lib.rs
- docs/includes/export-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Allow editing custom exercises correctly

- apps/frontend/app/components/fitness.tsx
- apps/frontend/app/lib/state/fitness.ts
- apps/frontend/app/routes/_dashboard.fitness.$action.tsx
> Allow empty exercises in workout templates 

- apps/frontend/app/routes/_dashboard.fitness.$action.tsx
- apps/frontend/app/routes/_dashboard.settings.preferences.tsx
- apps/frontend/app/routes/actions.tsx
- crates/utils/dependent/src/lib.rs
> Do not include special seasons for shows when updating progress

- docs/content/contributing.md
Hi :wave:,
I went through the contribution guide and this MR solves two obstacles I had while setting up the project.
Let me know if you want anything changed.
```bash
$ ryot git:(main) caddy run --config 'ci/Caddyfile'
2025/01/12 13:39:36.959 INFO    using provided configuration    {"config_file": "ci/Caddyfile", "config_adapter": ""}
Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle': ci/Caddyfile:34 - Error during parsing: unrecognized directive: {{ - are you sure your Caddyfile structure (nesting and braces) is correct?
$ ryot git:(main) caddy version
2.6.2
```
> docs: improve contribution guide

- crates/models/media/src/lib.rs
- crates/utils/dependent/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Allow order by times consumed

- crates/services/importer/src/trakt.rs
> Allow importing "Collection" from Trakt.tv

- apps/frontend/app/routes/_dashboard.fitness.$entity.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.$entity.list.tsx
> Display day of week for fitness entities

- README.md
- docs/content/configuration.md
- docs/content/guides/authentication.md
- docs/content/integrations.md
- libs/transactional/emails/PurchaseComplete.tsx
> Update outdated links

- apps/frontend/app/components/common.tsx
- apps/frontend/app/lib/generals.tsx
- apps/frontend/app/routes/_dashboard.collections.list.tsx
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/_dashboard.media.groups.$action.tsx
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.people.$action.tsx
- crates/models/dependent/src/lib.rs
- crates/models/media/src/lib.rs
- crates/utils/database/src/lib.rs
- crates/utils/dependent/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Advanced filter collections

- apps/frontend/app/lib/state/fitness.ts
- apps/frontend/app/routes/_dashboard.fitness.$action.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.list.tsx
- docs/content/index.md
> Fix bug in workout logging

- apps/frontend/app/components/common.tsx
- apps/frontend/app/routes/_dashboard.fitness.$entity.list.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.list.tsx
- crates/services/cache/src/lib.rs
> Fix fitness entity list page when no elements

- apps/frontend/app/components/fitness.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.item.$id._index.tsx
> Change id for superset

- crates/services/importer/src/mediatracker.rs
> Fixed media tracker import if user has custom lists

- apps/frontend/app/lib/hooks.ts
- apps/frontend/app/lib/state/general.tsx
- crates/migrations/src/lib.rs
- crates/migrations/src/m20230410_create_metadata.rs
- crates/migrations/src/m20250319_changes_for_issue_1294.rs
- crates/models/database/src/metadata.rs
- crates/models/dependent/src/lib.rs
- crates/models/media/src/lib.rs
- crates/services/cache/src/lib.rs
- crates/services/fitness/src/lib.rs
- crates/services/miscellaneous/src/lib.rs
- crates/services/user/src/lib.rs
- crates/utils/database/src/lib.rs
- crates/utils/dependent/src/lib.rs
- Simplified the ordering logic in the user service query by replacing the multi-line order_by method with order_by_desc for improved readability.
- Ensured the order of attributes remains compliant with coding standards.
Fixes #1294.
> New recommendation strategy

- apps/frontend/app/lib/state/general.tsx
- apps/frontend/app/lib/utilities.server.ts
- apps/frontend/app/routes/_dashboard.tsx
> Increase expiry for onboarding tour cookie

- apps/frontend/app/components/common.tsx
- apps/frontend/app/components/media.tsx
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.tsx
- crates/models/database/src/review.rs
- crates/models/user/src/lib.rs
- crates/utils/database/src/lib.rs
- crates/utils/dependent/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Allow reviewing out of 10

- crates/services/importer/src/generic_json.rs
> Import GenericJson provider_watched_on

- apps/frontend/app/routes/_dashboard.settings.notifications.tsx
- crates/migrations/src/lib.rs
- crates/migrations/src/m20250403_changes_for_issue_1330.rs
- crates/models/enum/src/lib.rs
- crates/services/miscellaneous/src/lib.rs
- crates/utils/dependent/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Send notifications when item is removed from monitoring

- apps/frontend/app/routes/_dashboard.collections.list.tsx
- apps/frontend/app/routes/_dashboard.tsx
- crates/models/common/src/lib.rs
- crates/models/database/src/collection_to_entity.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Add boolean collection extra information field type

- apps/frontend/app/lib/state/media.ts
- apps/frontend/app/routes/_dashboard.fitness.$entity.$id._index.tsx
- apps/frontend/app/routes/_dashboard.fitness.exercises.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.$action.$lot.tsx
- apps/frontend/app/routes/_dashboard.media.groups.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.media.people.item.$id._index.tsx
- apps/frontend/app/routes/_dashboard.tsx
- apps/frontend/app/routes/actions.tsx
> Assign multiple collections to media item at once

- apps/frontend/app/routes/_dashboard.fitness.$action.tsx
> Modal trigger to edit exercise details

- crates/services/importer/src/movary.rs
- crates/services/importer/src/trakt.rs
- crates/utils/dependent/src/lib.rs
> Aggregate metadata history before committing them

- Cargo.lock
- Cargo.toml
- crates/services/integration/Cargo.toml
- crates/services/integration/src/push/radarr.rs
- crates/services/integration/src/push/sonarr.rs
> Remove radarr and sonarr api rs

- apps/frontend/app/components/common.tsx
- crates/utils/database/src/lib.rs
> Resolve collection filter bugs

- crates/migrations/src/m20250423_changes_for_issue_1355.rs
> Unable to use postgres non-public schema

- apps/frontend/app/lib/state/fitness.ts
- apps/frontend/app/routes/_dashboard.fitness.$entity.$id._index.tsx
- apps/frontend/app/routes/_dashboard.settings.profile-and-sharing.tsx
- apps/frontend/app/routes/_dashboard.tsx
- crates/models/fitness/src/lib.rs
- crates/services/fitness/src/lib.rs
- crates/utils/dependent/src/lib.rs
- docs/includes/export-schema.ts
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Fix regression for DateTimePicker

- apps/frontend/app/routes/_dashboard.settings.imports-and-exports._index.tsx
- apps/frontend/app/routes/_dashboard.settings.integrations.tsx
- crates/models/media/src/lib.rs
- crates/services/importer/src/jellyfin.rs
- crates/services/integration/src/lib.rs
- crates/services/integration/src/push/jellyfin.rs
- crates/utils/external/src/lib.rs
- libs/generated/src/graphql/backend/graphql.ts
- libs/generated/src/graphql/backend/types.generated.ts
> Allow empty passwords for Jellyfin

- crates/providers/src/itunes.rs
> Podcast updation strategy

- apps/frontend/app/routes/_dashboard.media.item.$id._index.tsx
> Refactor date handling to use UTC string conversion

- apps/website/app/lib/components/ui/turnstile.tsx
- apps/website/app/lib/config.server.ts
- apps/website/app/routes/_index.tsx
Consolidate Turnstile keys in the server variables schema and streamline the integration by removing unused keys. Update the contact form to ensure the email field is required and correctly set IDs.
> Refactor Turnstile integration and update contact form validation
