docs/guides/video-games.md
IGDB documentation about 60 days token expiry referees to the tokens acquired by `https://id.twitch.tv/oauth2/token`, not the `Client ID` and `Client Secret`, and you correctly generate new token here https://github.com/IgnisDa/ryot/blob/f0d4d2c021a69695e60dbe280d2e34b993dd8414/apps/backend/src/utils.rs#L334-L338 so there is no need for any user action after submitting initial `Client ID` and `Client Secret`.
PS: I like you project very much
=> remove instructions to create new Twitch Access Token every 60 days

apps/frontend/src/lib/components/MediaItem.tsx
Having the box-shadow and border-radius on two different elements resulted in a small gap being visible between a rectangular box shadow and an image with rounded corners. The `sx` prop does not allow targeting the underlying `Image` component directly (which is what the `radius` prop is targeting), but the mantine Styles API (used via the `styles` prop) does.
**Before**
**After**
=> fix(frontend): apply box-shadow and border-radius to same elements

apps/frontend/src/lib/components/MediaDetailsLayout.tsx
Some media item only have one image available, a carousel is not needed on those cases. This PR aims to fix that.
Before : 
After :
=> fix(frontend): fix media item images always displayed as carousel

Cargo.lock, apps/backend/Cargo.toml, apps/frontend/src/lib/components/MediaDetailsLayout.tsx
The Carousel component doesn't have any support for lazy loading inner content. This can mean tens of megabytes of data transfer occur for some shows due to having a large number of images available. A simple workaround for this is to only load the visible image component, along with its immediate neighbors. Loading the immediate neighbors ensures the user experience remains smooth (not preloading those images can cause some elements to jump around as the image loads in).
This was just an idea that popped into my head as a quick workaround after the discussion in https://github.com/IgnisDa/ryot/issues/263#issuecomment-1680295643. Happy to shelve this idea if you'd prefer a cleaner solution.
=> perf(frontend): lazy load carousel images

apps/frontend/src/pages/media/people/index.tsx
Add a margin bottom "xs" to Title of people item (the same value as the margin on media item h3 titles)
Before: 
After:
=> fix(frontend): add spacing to h3 titles on people item

Cargo.lock, apps/backend/Cargo.toml, apps/backend/src/entities/metadata.rs, apps/backend/src/migrator/m20230901_create_partial_metadata.rs, apps/backend/src/migrator/m20230919_change_foreign_keys.rs, apps/backend/src/migrator/mod.rs, apps/backend/src/miscellaneous/resolver.rs
=> Bring back MySQL support 

docs/content/integrations.md
A plugin for [Flow Launcher](https://www.flowlauncher.com/) that allows you to quickly search your ryot tracker by media category.
=> Add Flow Launcher plugin to integrations docs

Cargo.lock, apps/backend/Cargo.toml, apps/backend/src/entities/calendar_event.rs, apps/backend/src/miscellaneous/resolver.rs, apps/backend/src/models.rs, apps/frontend/src/pages/fitness/exercises/current-workout.tsx, libs/database/src/migrations/m20231025_remove_duplicate_calendar_events.rs, libs/database/src/migrations/mod.rs
=> Remove duplicate calendar events

apps/backend/ci/build-app.sh
No idea why we need this but not before. I guess it is because we always pull the latest version of image `lukemathwalker/cargo-chef`. I suggest you to pin it to a more specific version.
=> Add target arch

Cargo.lock, Dockerfile, apps/backend/Cargo.toml
In this `dockerfile`, we switch the compilation target from `musl` to `gnu`. In addition, the `x86_64` target which was previously compiled with `gcc` is now switched to `clang` so we can have a more uniform experience between two targets.
After #544, we will switch the base image for the backend to `gcr.io/distroless/static-debian12` which is even lighter than `alpine` and has `glibc`.
=> use glibc instead of musl

libs/rs-utils/src/length_vec.rs
without this cargo test does not build properly:
error message:
```
error[E0432]: unresolved import `length_vec`
--> libs/rs-utils/src/length_vec.rs:13:5
|
3 | use length_vec::LengthVec;
|     ^^^^^^^^^^ use of undeclared crate or module `length_vec`
error: aborting due to 1 previous error
For more information about this error, try `rustc --explain E0432`.
Couldn't compile the test.
```
=> fix LengthVec import in rs_utils test

apps/backend/src/providers/audible.rs
changed suffix for au locale from .co.au to .com.au
Discovered this after getting "failed to lookup address information: Name or service not known" error when importing audio books from ABS.
Let me know if this should be created against a different branch.
Thanks!
=> Update audible.rs - fix suffix for au locale

Dockerfile
Fixes errors with invocations of "ps" terminal command...
Current master/latest contains some code/libraries that invoke "ps" command under certain circumstances (perhaps specific architectures or such).
Example of error this meant to solve:
```
[backend] 2024-08-06T01:06:23.929688Z  INFO sea_orm_migration::migrator: Applying all pending migrations
[backend] 2024-08-06T01:06:23.935904Z  INFO sea_orm_migration::migrator: No pending migrations
[backend] thread 'main' panicked at apps/backend/src/main.rs:159:28:
[backend] called `Result::unwrap()` on an `Err` value: ParseError(())
[backend] BACKEND_PORT=5000 /usr/local/bin/ryot exited with code 101
node:events:492
throw er; // Unhandled 'error' event
^
Error: spawn ps ENOENT
at ChildProcess._handle.onexit (node:internal/child_process:286:19) …
```
=> Fix missing "ps" terminal command on app crash/exit

apps/backend/src/miscellaneous.rs
There is a bug in the following condition:
- Import a manga and place it into a collection without downloading metadata
- Perform background tasks
This will result in the manga being marked as finished due to the episode count being 0. Modifying the condition to ensure that we arent marking something as finished without any watch history addresses this problem. This issue is extremely prevalent in the `Sync to Owned collection` function.
=> Addressed bug with Finished Condition during background tasks

crates/providers/src/anilist/media_details.graphql, crates/providers/src/anilist/mod.rs
This works but for some reason my IDE is confused about the existence of `use media_details_query::MediaStatus;` so maybe I need to add something else too. Not sure because it compiles and works.
see: https://katsurin.com/docs/anilist-node/global.html#MediaStatus
=> Introduced media status for anilist

crates/services/miscellaneous/src/lib.rs
We assumed the user was using UTC as the timezone so when we perform the check in progressUpdateInput depending on the timezone we sometimes incorrectly mark things as InThePast Rather Than Update for progress state
=> Resolved bug where we assumed timezone

crates/services/integration/src/komga.rs
e31071f5242e1f9fb5a0f537d0a858cd1808880a introduced an issue with the komga urls due to doubling up on trailing slash.
=> Resolved bug with komga urls 

crates/services/importer/src/jellyfin.rs
This slash causes the URL to always contain a double slash which broke the import.
=> fix: unnecessary slash

Cargo.lock, crates/models/common/src/lib.rs, crates/models/database/src/collection.rs, crates/models/dependent/src/lib.rs, crates/services/exporter/Cargo.toml, crates/services/exporter/src/lib.rs, crates/services/importer/src/generic_json.rs, docs/includes/export-schema.ts
=> Export workout collections

apps/frontend/app/routes/auth.tsx, docs/content/guides/authentication.md
Fixes #1284.
- Add documentation for `autoOidcLaunch` parameter
- Clarify how to access authentication page when local auth is disabled
- Improve explanation of OIDC authentication flow
=> Auto launch OIDC

crates/services/integration/src/lib.rs, crates/services/integration/src/sink/emby.rs, crates/services/integration/src/sink/generic_json.rs, crates/services/integration/src/sink/jellyfin.rs, crates/services/integration/src/sink/kodi.rs, crates/services/integration/src/sink/plex.rs, docs/content/integrations.md
Fixes #1278.
- Add `MarkPlayed` to the list of supported webhook events
- Clarify event configuration for Jellyfin integration
=> Add support for MarkPlayed event from Jellyfin

apps/frontend/app/components/common.tsx, apps/frontend/app/lib/common.tsx, apps/frontend/app/routes/_dashboard._index.tsx
- Changed cacheId prop in ExpireCacheKeyButton and SectionTitleWithRefreshIcon components to be optional.
- Adjusted related component usage in the dashboard to reflect the updated prop definition.
Fixes #1297.
=> Move recommendations fetching to client side
